import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        tertiary: "#625e55",
        "on-tertiary-fixed": "#1e1c14",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#554300",
        "on-surface-variant": "#4d4635",
        "secondary-fixed-dim": "#c6c7c2",
        "outline-variant": "#d0c5af",
        "surface-container": "#efeeeb",
        "surface-tint": "#735c00",
        outline: "#7f7663",
        "surface-bright": "#faf9f6",
        primary: "#735c00",
        "inverse-primary": "#e9c349",
        "secondary-fixed": "#e3e3de",
        "surface-variant": "#e3e2e0",
        "surface-container-highest": "#e3e2e0",
        "inverse-on-surface": "#f2f1ee",
        "on-error": "#ffffff",
        surface: "#faf9f6",
        "surface-dim": "#dbdad7",
        "on-secondary-fixed": "#1a1c19",
        "surface-container-low": "#f4f3f1",
        "on-secondary-fixed-variant": "#454744",
        secondary: "#5d5f5b",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2f312f",
        "on-primary": "#ffffff",
        "on-secondary-container": "#62635f",
        "tertiary-fixed": "#e8e2d6",
        "on-background": "#1a1c1a",
        "on-tertiary-fixed-variant": "#4a473e",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffe088",
        "on-tertiary-container": "#48453c",
        "on-primary-fixed-variant": "#574500",
        "tertiary-container": "#b7b2a7",
        background: "#faf9f6",
        "on-primary-fixed": "#241a00",
        error: "#ba1a1a",
        "tertiary-fixed-dim": "#cbc6ba",
        "on-surface": "#1a1c1a",
        "primary-fixed-dim": "#e9c349",
        "primary-container": "#d4af37",
        "surface-container-high": "#e9e8e5",
        "secondary-container": "#e0e0db",
        "wedding-fucsia": "#D81B60",
        "wedding-coral": "#FF7043",
        "wedding-amarillo": "#FFC107",
        "wedding-verde": "#9EAD26",
        "wedding-turquesa": "#00ACC1",
        "wedding-azul": "#0D47A1",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "section-padding-desktop": "120px",
        "section-padding-mobile": "64px",
        unit: "8px",
        gutter: "24px",
        "container-max": "1200px",
      },
      fontFamily: {
        "label-caps": ["var(--font-montserrat)", "sans-serif"],
        "body-md": ["var(--font-montserrat)", "sans-serif"],
        "body-lg": ["var(--font-montserrat)", "sans-serif"],
        "headline-sm": ["var(--font-playfair)", "serif"],
        "headline-md": ["var(--font-playfair)", "serif"],
        "display-lg": ["var(--font-playfair)", "serif"],
        "display-lg-mobile": ["var(--font-playfair)", "serif"],
      },
    },
  },
  plugins: [],
};

export default config;
